version: '2'
services:

  flask-app:
    ports:
        - '80:80'
    volumes:
      - './flask-app/app:/app'    
    command: bash -c "while true; do sleep 1; done"    
    environment:
      - FLASK_APP=app/main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'

  pgadmin:
    ports:
      - 5050:5050

  swagger-ui:
    environment:
      - API_URL=http://dev.api.backend-stack.com/v1/swagger/
    ports:
      - 8080:8080